import type { PdfReferenceScenario, SiteConstants } from './types'

export const PDF_SOURCE = {
  document:
    'C:/Users/Arq. David Agudelo/Documents/Factibilidad junio 2026/output/pdf/factibilidad_KR9B_117A55.pdf',
  publicHref: '/static/factibilidad_KR9B_117A55.pdf',
  revisionDate: '2026-06-30',
  note:
    'Fuente de verdad documental del modelador preliminar; no reemplaza licencia, Curaduria, Aerocivil, topografia ni perfil vial oficial.',
}

export const SITE_CONSTANTS: SiteConstants = {
  caseId: 'KR9B_117A55',
  name: 'KR 9B #117A-55',
  location: 'Santa Barbara, Usaquen',
  width: 12.992,
  depth: 25.108,
  area: 326.184,
  officialPerimeter: 76.187,
  iceIndex: 5,
  defaultSellableEfficiency: 0.78,
  drawingScale: 18,
  source: {
    document: PDF_SOURCE.document,
    publicHref: PDF_SOURCE.publicHref,
    revisionDate: PDF_SOURCE.revisionDate,
    pages: [2, 3, 4, 5, 6, 7, 9, 10],
    note: PDF_SOURCE.note,
  },
}

export const NORMATIVE_RULES = {
  treatment: 'Renovacion Urbana',
  minFloors: 2,
  preliminaryMaxHeight: 27,
  baseLateralOnsetHeight: 11.4,
  ecosLateralOnsetHeight: 15.7,
  minFloorHeight: 2.3,
  minSideSetback: 4,
  minUsefulUpperWidth: 2.4,
  rearSetbackBands: [
    { maxHeight: 12, setback: 4 },
    { maxHeight: 18, setback: 5 },
    { maxHeight: 27, setback: 6 },
  ],
  pendingConfirmations: [
    'Levantamiento topografico',
    'Perfil oficial KR 9B y retrocesos contra espacio publico',
    'Confirmacion Aerocivil',
    'Concepto SDP/Curaduria sobre ECOS, ICe efectivo, obligaciones y empates',
    'Expedientes de vecinos',
  ],
}

export const PDF_STUDY_FLOOR_HEIGHT = 3

export const REFERENCE_SCENARIOS: PdfReferenceScenario[] = [
  {
    floors: 5,
    studyFloorHeight: PDF_STUDY_FLOOR_HEIGHT,
    totalHeight: 15,
    ecosMode: false,
    rearSetback: 5,
    lateralOnsetHeight: 11.4,
    effectiveArea: 1145.25,
    iceMargin: 485.67,
    status: 'factible normativamente',
    sourcePage: 4,
  },
  {
    floors: 5,
    studyFloorHeight: PDF_STUDY_FLOOR_HEIGHT,
    totalHeight: 15,
    ecosMode: true,
    rearSetback: 5,
    lateralOnsetHeight: 15.7,
    effectiveArea: 1306.12,
    iceMargin: 324.8,
    status: 'factible condicionado',
    sourcePage: 4,
  },
  {
    floors: 6,
    studyFloorHeight: PDF_STUDY_FLOOR_HEIGHT,
    totalHeight: 18,
    ecosMode: false,
    rearSetback: 5,
    lateralOnsetHeight: 11.4,
    effectiveArea: 1245.62,
    iceMargin: 385.3,
    status: 'factible condicionado',
    sourcePage: 5,
  },
  {
    floors: 6,
    studyFloorHeight: PDF_STUDY_FLOOR_HEIGHT,
    totalHeight: 18,
    ecosMode: true,
    rearSetback: 5,
    lateralOnsetHeight: 15.7,
    effectiveArea: 1406.47,
    iceMargin: 224.45,
    status: 'factible condicionado',
    sourcePage: 5,
  },
  {
    floors: 7,
    studyFloorHeight: PDF_STUDY_FLOOR_HEIGHT,
    totalHeight: 21,
    ecosMode: false,
    rearSetback: 6,
    lateralOnsetHeight: 11.4,
    effectiveArea: 1269.06,
    iceMargin: 361.86,
    status: 'factible condicionado',
    sourcePage: 6,
  },
  {
    floors: 7,
    studyFloorHeight: PDF_STUDY_FLOOR_HEIGHT,
    totalHeight: 21,
    ecosMode: true,
    rearSetback: 6,
    lateralOnsetHeight: 15.7,
    effectiveArea: 1425.91,
    iceMargin: 205.01,
    status: 'factible condicionado',
    sourcePage: 6,
  },
  {
    floors: 8,
    studyFloorHeight: PDF_STUDY_FLOOR_HEIGHT,
    totalHeight: 24,
    ecosMode: false,
    rearSetback: 6,
    lateralOnsetHeight: 11.4,
    effectiveArea: 1361.44,
    iceMargin: 269.48,
    status: 'requiere confirmacion de Curaduria',
    sourcePage: 7,
  },
  {
    floors: 8,
    studyFloorHeight: PDF_STUDY_FLOOR_HEIGHT,
    totalHeight: 24,
    ecosMode: true,
    rearSetback: 6,
    lateralOnsetHeight: 15.7,
    effectiveArea: 1518.29,
    iceMargin: 112.63,
    status: 'requiere confirmacion de Curaduria',
    sourcePage: 7,
  },
]
