import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'

type Manifest = {
  sources: Array<{
    id: string
    title: string
    authority: string
    officialUrl: string
    sourceFamily: string
    legalStatus: string
    versionDate: string
    dataDate: string
    ragRole: string
    indexText: boolean
    indexSpatial: boolean
  }>
}

const workspaceRoot = process.cwd()
const manifestPath = resolve(
  workspaceRoot,
  process.env.RAG_SOURCE_MANIFEST_PATH ?? 'rag/sources/sources.manifest.json',
)
const factsPath = resolve(
  workspaceRoot,
  process.env.RAG_SPATIAL_FACTS_PATH ?? 'data/spatial/facts/KR9B_117A55.json',
)
const workerDataRoot = resolve(workspaceRoot, 'cloudflare-worker/src/data')

const manifest = JSON.parse(readFileSync(manifestPath, 'utf8')) as Manifest
const spatialFacts = JSON.parse(readFileSync(factsPath, 'utf8')) as unknown

mkdirSync(workerDataRoot, { recursive: true })
writeGeneratedFile(
  resolve(workerDataRoot, 'sources.generated.ts'),
  'SOURCES',
  manifest.sources.map((source) => ({
    id: source.id,
    title: source.title,
    authority: source.authority,
    officialUrl: source.officialUrl,
    sourceFamily: source.sourceFamily,
    legalStatus: source.legalStatus,
    versionDate: source.versionDate,
    dataDate: source.dataDate,
    ragRole: source.ragRole,
    indexText: source.indexText,
    indexSpatial: source.indexSpatial,
  })),
  "import type { GeneratedSource } from '../types'\n",
  'GeneratedSource[]',
)
writeGeneratedFile(
  resolve(workerDataRoot, 'spatialFacts.generated.ts'),
  'SPATIAL_FACTS',
  spatialFacts,
  "import type { GeneratedSpatialFacts } from '../types'\n",
  'GeneratedSpatialFacts',
)

console.log('Cloudflare Worker data generated.')
console.log(`- ${manifest.sources.length} sources -> cloudflare-worker/src/data/sources.generated.ts`)
console.log('- spatial facts -> cloudflare-worker/src/data/spatialFacts.generated.ts')

function writeGeneratedFile(
  path: string,
  exportName: string,
  value: unknown,
  imports: string,
  typeName: string,
): void {
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(
    path,
    [
      '/* This file is generated by rag/scripts/buildWorkerData.ts. Do not edit by hand. */',
      imports.trimEnd(),
      '',
      `export const ${exportName} = ${JSON.stringify(value, null, 2)} satisfies ${typeName}`,
      '',
    ].join('\n'),
    'utf8',
  )
}
